### ISSUE TITLE
Prototype error handling

### ISSUE THREAD

**Issue by victor-soloviev** [lumeohq/onvif-rs#1]
We need to prototype the error handling process. There are at least three levels, from which errors could occur:
- errors from the used transport-level client
- errors in SOAP responses
- errors on ONVIF level

Each level has its error type.

One way to provide a user of the library with information about what has gone wrong is to use a Result type with its Error being an enum. Each variant of this enum would represent one of the possible error types.

**Comment by chrisabruce** [comment]
fixed
