### ISSUE TITLE
Any reason not to publish on crates.io?

### ISSUE THREAD

**Issue by pedrocr** [lumeohq/onvif-rs#16]
It seems this is not published on crates.io. The `onvif` crate name is still available, but `onvif-rs` is taken by a very incomplete implementation. Any reason not to publish it?

**Comment by chrisabruce** [comment]
We haven't quite finished this yet.  We have another xsd/wsdl parser that we continue to work on to generate this client.

We hope to have first release in the next 2 weeks or so.

**Comment by kate-goldenring** [comment]
Following up on this issue. Are you all looking into publishing a crate?
