### ISSUE TITLE
UUID of ONVIF Camera

### ISSUE THREAD

**Issue by babashunsuke** [lumeohq/onvif-rs#88]
This may not be an issue but I believe the discovery had better return UUID of the target camera.

<wsadis:Address>urn:uuid:ea84ffa0-7b80-1ca9-51a1-dc87aa828f96</wsadis:Address>

This is necessary to identify an camera to manage. 
[example.txt](https://github.com/lumeohq/onvif-rs/files/8193973/example.txt)

**Comment by Alibirb** [comment]
This is implemented now. The `Device` struct now contains an `address` field with the UUID.

See https://github.com/lumeohq/onvif-rs/pull/116
